import { ProductCategory, ProductCollection, Region } from "@medusajs/medusa"
import { PricedProduct } from "@medusajs/medusa/dist/types/pricing"
import { ProductCategoryWithChildren } from "types/global"

export const MOCK_REGIONS: Region[] = [
  {
    id: "reg_default_us",
    name: "North America",
    currency_code: "usd",
    tax_rate: 0,
    tax_rates: [],
    tax_code: "standard",
    countries: [
      { id: 1, iso_2: "us", iso_3: "usa", num_code: 840, name: "United States", display_name: "United States", region_id: "reg_default_us" },
      { id: 2, iso_2: "ca", iso_3: "can", num_code: 124, name: "Canada", display_name: "Canada", region_id: "reg_default_us" },
    ],
    payment_providers: [{ id: "stripe", is_installed: true }],
    fulfillment_providers: [{ id: "manual", is_installed: true }],
    includes_tax: false,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
    deleted_at: null,
    metadata: null,
  } as unknown as Region,
  {
    id: "reg_default_eu",
    name: "Europe",
    currency_code: "eur",
    tax_rate: 20,
    tax_rates: [],
    tax_code: "standard",
    countries: [
      { id: 3, iso_2: "de", iso_3: "deu", num_code: 276, name: "Germany", display_name: "Germany", region_id: "reg_default_eu" },
      { id: 4, iso_2: "fr", iso_3: "fra", num_code: 250, name: "France", display_name: "France", region_id: "reg_default_eu" },
      { id: 5, iso_2: "gb", iso_3: "gbr", num_code: 826, name: "United Kingdom", display_name: "United Kingdom", region_id: "reg_default_eu" },
    ],
    payment_providers: [{ id: "stripe", is_installed: true }],
    fulfillment_providers: [{ id: "manual", is_installed: true }],
    includes_tax: true,
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
    deleted_at: null,
    metadata: null,
  } as unknown as Region,
]

export const MOCK_COLLECTIONS: ProductCollection[] = [
  {
    id: "col_sports_cars",
    title: "Sports Cars",
    handle: "sports_cars",
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
    deleted_at: null,
    metadata: null,
  } as unknown as ProductCollection,
  {
    id: "col_luxury_sedans",
    title: "Luxury Sedans",
    handle: "luxury_sedans",
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
    deleted_at: null,
    metadata: null,
  } as unknown as ProductCollection,
  {
    id: "col_supercars",
    title: "Supercars",
    handle: "supercars",
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
    deleted_at: null,
    metadata: null,
  } as unknown as ProductCollection,
]

export const MOCK_CATEGORIES: ProductCategoryWithChildren[] = [
  {
    id: "cat_coupes",
    name: "Performance Coupes",
    handle: "performance_coupes",
    description: "High performance sports coupes with precision German and Italian engineering",
    is_active: true,
    is_internal: false,
    rank: 0,
    parent_category_id: null,
    category_children: [],
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  } as unknown as ProductCategoryWithChildren,
  {
    id: "cat_sedans",
    name: "Executive Sedans",
    handle: "executive_sedans",
    description: "Refined luxury sedans with twin turbo power and all wheel drive",
    is_active: true,
    is_internal: false,
    rank: 1,
    parent_category_id: null,
    category_children: [],
    created_at: new Date("2024-01-01").toISOString(),
    updated_at: new Date("2024-01-01").toISOString(),
  } as unknown as ProductCategoryWithChildren,
]

export const MOCK_PRODUCTS: PricedProduct[] = [
  {
    id: "prod_porsche_911",
    title: "Porsche 911 Carrera S",
    subtitle: "3.0L Twin Turbocharged Boxer 6 Engine with 443 HP",
    description: "The iconic rear engine sports car featuring an eight speed dual clutch transmission, active suspension management, and sport exhaust system.",
    handle: "porsche_911_carrera_s",
    is_giftcard: false,
    status: "published",
    thumbnail: "https://pngimg.com/d/porsche_PNG10613.png",
    images: [
      { id: "img_p911_1", url: "https://pngimg.com/d/porsche_PNG10613.png" },
    ],
    options: [
      {
        id: "opt_trim_911",
        title: "Trim",
        product_id: "prod_porsche_911",
        values: [
          { id: "opt_val_911_carrera", value: "Carrera S" },
          { id: "opt_val_911_4s", value: "Carrera 4S" },
        ],
      },
    ],
    variants: [
      {
        id: "var_p911_s",
        title: "Carrera S",
        sku: "POR_911_S",
        inventory_quantity: 4,
        calculated_price: 13000000,
        original_price: 13000000,
        calculated_price_type: "default",
        prices: [
          { id: "pr_p911_usd", currency_code: "usd", amount: 13000000 },
          { id: "pr_p911_eur", currency_code: "eur", amount: 12500000 },
        ],
        options: [{ id: "opt_val_911_carrera", option_id: "opt_trim_911", value: "Carrera S" }],
      },
      {
        id: "var_p911_4s",
        title: "Carrera 4S",
        sku: "POR_911_4S",
        inventory_quantity: 2,
        calculated_price: 14000000,
        original_price: 14000000,
        calculated_price_type: "default",
        prices: [
          { id: "pr_p911_4s_usd", currency_code: "usd", amount: 14000000 },
          { id: "pr_p911_4s_eur", currency_code: "eur", amount: 13500000 },
        ],
        options: [{ id: "opt_val_911_4s", option_id: "opt_trim_911", value: "Carrera 4S" }],
      },
    ],
    collection_id: "col_sports_cars",
    collection: MOCK_COLLECTIONS[0],
    categories: [MOCK_CATEGORIES[0]],
    material: "Aluminum and High Strength Steel Composite",
    origin_country: "Germany",
    weight: 1535,
    created_at: new Date("2024-01-01"),
    updated_at: new Date("2024-01-01"),
  } as unknown as PricedProduct,
  {
    id: "prod_bmw_m4",
    title: "BMW M4 Competition",
    subtitle: "3.0L M TwinPower Turbo Inline 6 with 503 HP",
    description: "Track ready performance coupe with M xDrive all wheel drive, carbon fiber roof, and adaptive M suspension.",
    handle: "bmw_m4_competition",
    is_giftcard: false,
    status: "published",
    thumbnail: "https://pngimg.com/d/bmw_PNG99547.png",
    images: [
      { id: "img_bmw_m4_1", url: "https://pngimg.com/d/bmw_PNG99547.png" },
    ],
    options: [
      {
        id: "opt_bmw_trim",
        title: "Drivetrain",
        product_id: "prod_bmw_m4",
        values: [
          { id: "opt_val_m4_rwd", value: "Rear Wheel Drive" },
          { id: "opt_val_m4_xdrive", value: "M xDrive All Wheel Drive" },
        ],
      },
    ],
    variants: [
      {
        id: "var_m4_comp",
        title: "Competition M xDrive",
        sku: "BMW_M4_COMP",
        inventory_quantity: 6,
        calculated_price: 8600000,
        original_price: 8600000,
        calculated_price_type: "default",
        prices: [
          { id: "pr_m4_usd", currency_code: "usd", amount: 8600000 },
          { id: "pr_m4_eur", currency_code: "eur", amount: 8200000 },
        ],
        options: [{ id: "opt_val_m4_xdrive", option_id: "opt_bmw_trim", value: "M xDrive All Wheel Drive" }],
      },
    ],
    collection_id: "col_sports_cars",
    collection: MOCK_COLLECTIONS[0],
    categories: [MOCK_CATEGORIES[0]],
    material: "Carbon Fiber and Ultra High Tensile Steel",
    origin_country: "Germany",
    weight: 1775,
    created_at: new Date("2024-01-02"),
    updated_at: new Date("2024-01-02"),
  } as unknown as PricedProduct,
  {
    id: "prod_mercedes_amg_gt",
    title: "Mercedes AMG GT Coupe",
    subtitle: "4.0L V8 Biturbo Handcrafted Engine with 577 HP",
    description: "Grand touring supercar with AMG performance 4MATIC plus all wheel drive, active aerodynamics, and race telemetry.",
    handle: "mercedes_amg_gt_coupe",
    is_giftcard: false,
    status: "published",
    thumbnail: "https://pngimg.com/d/mercedes_benz_PNG101880.png",
    images: [
      { id: "img_amg_gt_1", url: "https://pngimg.com/d/mercedes_benz_PNG101880.png" },
    ],
    options: [
      {
        id: "opt_amg_spec",
        title: "Edition",
        product_id: "prod_mercedes_amg_gt",
        values: [{ id: "opt_val_amg_gt63", value: "GT 63 4MATIC Plus" }],
      },
    ],
    variants: [
      {
        id: "var_amg_gt63",
        title: "GT 63",
        sku: "MB_AMG_GT63",
        inventory_quantity: 3,
        calculated_price: 17500000,
        original_price: 17500000,
        calculated_price_type: "default",
        prices: [
          { id: "pr_amg_usd", currency_code: "usd", amount: 17500000 },
          { id: "pr_amg_eur", currency_code: "eur", amount: 16800000 },
        ],
        options: [{ id: "opt_val_amg_gt63", option_id: "opt_amg_spec", value: "GT 63 4MATIC Plus" }],
      },
    ],
    collection_id: "col_supercars",
    collection: MOCK_COLLECTIONS[2],
    categories: [MOCK_CATEGORIES[0]],
    material: "Aluminum Spaceframe Architecture",
    origin_country: "Germany",
    weight: 1895,
    created_at: new Date("2024-01-03"),
    updated_at: new Date("2024-01-03"),
  } as unknown as PricedProduct,
  {
    id: "prod_audi_rs7",
    title: "Audi RS7 Sportback",
    subtitle: "4.0L Twin Turbo V8 with 591 HP and Quattro",
    description: "High performance executive sportback with quattro all wheel drive, dynamic all wheel steering, and matrix LED lighting.",
    handle: "audi_rs7_sportback",
    is_giftcard: false,
    status: "published",
    thumbnail: "https://pngimg.com/d/audi_PNG99484.png",
    images: [
      { id: "img_audi_rs7_1", url: "https://pngimg.com/d/audi_PNG99484.png" },
    ],
    options: [
      {
        id: "opt_audi_spec",
        title: "Package",
        product_id: "prod_audi_rs7",
        values: [{ id: "opt_val_audi_perf", value: "Performance Edition" }],
      },
    ],
    variants: [
      {
        id: "var_audi_rs7",
        title: "RS7 Performance",
        sku: "AUDI_RS7_PERF",
        inventory_quantity: 5,
        calculated_price: 12800000,
        original_price: 12800000,
        calculated_price_type: "default",
        prices: [
          { id: "pr_rs7_usd", currency_code: "usd", amount: 12800000 },
          { id: "pr_rs7_eur", currency_code: "eur", amount: 12200000 },
        ],
        options: [{ id: "opt_val_audi_perf", option_id: "opt_audi_spec", value: "Performance Edition" }],
      },
    ],
    collection_id: "col_luxury_sedans",
    collection: MOCK_COLLECTIONS[1],
    categories: [MOCK_CATEGORIES[1]],
    material: "Lightweight Aluminum and Steel Hybrid",
    origin_country: "Germany",
    weight: 2150,
    created_at: new Date("2024-01-04"),
    updated_at: new Date("2024-01-04"),
  } as unknown as PricedProduct,
  {
    id: "prod_ferrari_f8",
    title: "Ferrari F8 Tributo",
    subtitle: "3.9L Twin Turbo V8 Engine with 710 HP",
    description: "Mid rear engine supercar with titanium connecting rods, active side slip control, and F1 dual clutch transmission.",
    handle: "ferrari_f8_tributo",
    is_giftcard: false,
    status: "published",
    thumbnail: "https://pngimg.com/d/ferrari_PNG10665.png",
    images: [
      { id: "img_f8_1", url: "https://pngimg.com/d/ferrari_PNG10665.png" },
    ],
    options: [
      {
        id: "opt_f8_spec",
        title: "Configuration",
        product_id: "prod_ferrari_f8",
        values: [{ id: "opt_val_f8_coupe", value: "Berlinetta Coupe" }],
      },
    ],
    variants: [
      {
        id: "var_f8_coupe",
        title: "Berlinetta",
        sku: "FER_F8_TRIB",
        inventory_quantity: 2,
        calculated_price: 28000000,
        original_price: 28000000,
        calculated_price_type: "default",
        prices: [
          { id: "pr_f8_usd", currency_code: "usd", amount: 28000000 },
          { id: "pr_f8_eur", currency_code: "eur", amount: 26500000 },
        ],
        options: [{ id: "opt_val_f8_coupe", option_id: "opt_f8_spec", value: "Berlinetta Coupe" }],
      },
    ],
    collection_id: "col_supercars",
    collection: MOCK_COLLECTIONS[2],
    categories: [MOCK_CATEGORIES[0]],
    material: "Aerospace Grade Carbon Fiber and Extruded Aluminum",
    origin_country: "Italy",
    weight: 1435,
    created_at: new Date("2024-01-05"),
    updated_at: new Date("2024-01-05"),
  } as unknown as PricedProduct,
]
